from fpdf import FPDF
import json
import os
from translator import translate_text

def generate_bank_form(scheme_name, user_data, lang='hi'):
    pdf = FPDF()
    pdf.add_page()
    
    with open('../data/schemes.json', 'r') as f:
        schemes = json.load(f)
    
    scheme = schemes.get(scheme_name)
    if not scheme:
        return "Scheme not found!"
    

    font_path = "../fonts/NotoSansDevanagari-Regular.ttf"
    if os.path.exists(font_path):
        pdf.add_font('IndicFont', '', font_path, uni=True)
        pdf.set_font('IndicFont', size=12)
    else:
        pdf.set_font("Arial", size=12)

    title = scheme['title'] if lang == 'en' else translate_text(scheme['title'], lang)
    pdf.set_font_size(16)
    pdf.cell(0, 10, title, ln=True, align='C')
    pdf.ln(10)
    
    pdf.set_font_size(12)
    for field in scheme['fields']:
        label = field if lang == 'en' else translate_text(field, lang)
        value = user_data.get(field, '')
        pdf.cell(40, 10, f"{label}: ", border='B')
        pdf.cell(0, 10, value, border='B', ln=True)
        pdf.ln(5)
    
    note = "Generated by Vitt-Sahayata Banking Assistant"
    pdf.set_font_size(10)
    pdf.cell(0, 10, note, ln=True, align='C')
    
    filename = f"../generated_docs/{scheme_name}_{lang}.pdf"
    pdf.output(filename)
    return f"Form generated: {filename}"
